export default {
  LOGOUT: 'LOGOUT',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  REQUEST_ERROR: 'REQUEST_ERROR',
  SET_AUTH: 'SET_AUTH',

  GET_MOVIES: 'GET_MOVIES',
  SAVE_MOVIES: 'SAVE_MOVIES',
  MOVIE_REQUEST_ERROR: 'MOVIE_REQUEST_ERROR',
};
